src/main/java/muxar/dto/MusicArtist.java
package muxar.dto;

import com.hp.hpl.jena.graph.Node;
import com.hp.hpl.jena.graph.Triple;
import muxar.utils.Vocabulary;
import muxar.utils.Vocabulary.Property;

import java.io.Serializable;

public class MusicArtist implements Serializable{


	/**
	 * 
	 */
	private static final long serialVersionUID = 3897788812837866207L;
	private String name = "";
	private String image = "";
	private String resourceName = "";

	public MusicArtist() {
	}

	public Triple rdfIsArtist() {
		Node resource = Node.createURI(resourceName);
		Node type = Node.createURI(Vocabulary.RDF_URI + Property.RDF_TYPE);
		Node artistType = Node.createURI(Vocabulary.Type.ARTIST);

		return new Triple(resource, type, artistType);
	}
	
	public Triple rdfHasName() {
		Node artist = Node.createURI(resourceName);
		Node hasName = Node.createURI(Vocabulary.FOAF_URI + Property.FOAF_NAME);
		Node nameValue = Node.createLiteral(name);

		return new Triple(artist, hasName, nameValue);
	}
	
	public Triple rdfHasImage() {
		Node artist = Node.createURI(resourceName);
		Node hasImage = Node.createURI(Vocabulary.SCHEMA_URI + Property.SCHEMA_IMAGE);
		Node imageValue = Node.createURI(image);

		return new Triple(artist, hasImage, imageValue);
	}


	public MusicArtist(String name) {
		this.name = name;
	}

	public String getImage() {
		return image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getResourceName() {
		return resourceName;
	}

	public void setResourceName(String resourceName) {
		this.resourceName = resourceName;
	}

}

src/main/java/muxar/dto/MusicItem.java
package muxar.dto;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import muxar.utils.Vocabulary;
import muxar.utils.Vocabulary.Property;

import com.hp.hpl.jena.graph.Node;
import com.hp.hpl.jena.graph.Triple;

@JsonIgnoreProperties(ignoreUnknown = true)
public class MusicItem extends MusicRecording {

	public String getUrl() {
		return "http://www.last.fm/music/" + artist.getName() + "/" + name;
	}

	public Triple rdfIsMusicRecording() {
		Node resource = Node.createURI(resourceName);
		Node type = Node.createURI(Vocabulary.RDF_URI + Property.RDF_TYPE);
		Node songType = Node.createURI(Vocabulary.Type.SONG);

		return new Triple(resource, type, songType);
	}
	
	public Triple rdfHasName() {
		
		Node song = Node.createURI(resourceName);
		Node hasName = Node.createURI(Vocabulary.FOAF_URI + Property.FOAF_NAME);
		Node nameValue = Node.createLiteral(name);

		return new Triple(song, hasName, nameValue);
	}
	
	public Triple rdfHasArtist() {
		
		Node song = Node.createURI(resourceName);
		Node hasArtist = Node.createURI(Vocabulary.SCHEMA_URI + Property.SCHEMA_ARTIST);
		Node artistNode = Node.createURI(artist.getResourceName());

		return new Triple(song, hasArtist, artistNode);
	}
}

src/main/java/muxar/dto/MusicRecording.java
package muxar.dto;

public class MusicRecording {

	protected String resourceName="";
	protected String name="";
	protected MusicArtist artist;

	public MusicRecording() {
	}

	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public MusicArtist getArtist() {
		return artist;
	}
	public void setArtist(MusicArtist artist) {
		this.artist = artist;
	}
	public String getResourceName() {
		return resourceName;
	}
	public void setResourceName(String resourceName) {
		this.resourceName = resourceName;
	}

}

src/main/java/muxar/dto/User.java
package muxar.dto;

import muxar.gateway.domain.MusicFacebook;

/**
 * Created by Alice on 1/25/2016.
 */
public class User {
    private String userId;
    private String name;
    private String fbAccessToken;
    private MusicFacebook musicFacebook;

    public User() {
        super();
    }

    public User(String userId, String name, String fbAccessToken) {
        this.userId = userId;
        this.name = name;
        this.fbAccessToken = fbAccessToken;
        		
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getFbAccessToken() {
        return fbAccessToken;
    }

    public void setFbAccessToken(String fbAccessToken) {
        this.fbAccessToken = fbAccessToken;
    }

	public MusicFacebook getMusicFacebook() {
		return musicFacebook;
	}

	public void setMusicFacebook(MusicFacebook musicFacebook) {
		this.musicFacebook = musicFacebook;
	}
    
    
}

src/main/java/muxar/gateway/domain/Cursors.java
package muxar.gateway.domain;

/**
 * Created by Alice on 1/25/2016.
 */
public class Cursors {
    private String before;
    private String after;

    public String getBefore() {
        return before;
    }

    public void setBefore(String before) {
        this.before = before;
    }

    public String getAfter() {
        return after;
    }

    public void setAfter(String after) {
        this.after = after;
    }
}

src/main/java/muxar/gateway/domain/MusicFacebook.java
package muxar.gateway.domain;

import java.io.Serializable;
import java.util.List;

/**
 * Created by Alice on 1/25/2016.
 */
public class MusicFacebook implements Serializable{

    private List<MusicItemFacebook> data;
    private Paging paging;

    public List<MusicItemFacebook> getData() {
        return data;
    }

    public void setData(List<MusicItemFacebook> data) {
        this.data = data;
    }

    public Paging getPaging() {
        return paging;
    }

    public void setPaging(Paging paging) {
        this.paging = paging;
    }
}

src/main/java/muxar/gateway/domain/MusicItemFacebook.java
package muxar.gateway.domain;

import java.io.Serializable;

/**
 * Created by Alice on 1/25/2016.
 */
public class MusicItemFacebook implements Serializable{
    private String name;
    private String id;
    private String created_time;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getCreated_time() {
        return created_time;
    }

    public void setCreated_time(String created_time) {
        this.created_time = created_time;
    }
}

src/main/java/muxar/gateway/domain/Paging.java
package muxar.gateway.domain;

/**
 * Created by Alice on 1/25/2016.
 */
public class Paging {
    private Cursors cursors;

    public Cursors getCursors() {
        return cursors;
    }

    public void setCursors(Cursors cursors) {
        this.cursors = cursors;
    }
}

src/main/java/muxar/gateway/dto/DeletePlaylistWrapper.java
package muxar.gateway.dto;

public class DeletePlaylistWrapper {
	private String userId;
	private String token;
    private String playlistName;
    private String playlistId;
    private String playlistPrivacy;

	public DeletePlaylistWrapper(){
		
	}
    
	public DeletePlaylistWrapper(String userId, String token, String playlistId, String playlistName, String playlistPrivacy) {
		this.userId = userId;
		this.token = token;
		this.playlistId = playlistId;
		this.playlistName = playlistName;
		this.playlistPrivacy = playlistPrivacy;
	}
	
	public String getUserId() {
		return userId;
	}
	public void setUserId(String userId) {
		this.userId = userId;
	}
	public String getToken() {
		return token;
	}
	public void setToken(String token) {
		this.token = token;
	}
	public String getPlaylistName() {
		return playlistName;
	}

	public void setPlaylistName(String playlistName) {
		this.playlistName = playlistName;
	}

	public String getPlaylistId() {
		return playlistId;
	}

	public void setPlaylistId(String playlistId) {
		this.playlistId = playlistId;
	}

	public String getPlaylistPrivacy() {
		return playlistPrivacy;
	}

	public void setPlaylistPrivacy(String playlistPrivacy) {
		this.playlistPrivacy = playlistPrivacy;
	}
}

src/main/java/muxar/gateway/dto/DownloadRequest.java
package muxar.gateway.dto;

/**
 * Created by Alice on 1/30/2016.
 */
public class DownloadRequest {
    private String userId;
    private String token;
    private String playlistResource;

    public DownloadRequest() {
    }

    public DownloadRequest(String userId, String token, String playlistResource) {
        this.userId = userId;
        this.token = token;
        this.playlistResource = playlistResource;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getToken() {
        return token;
    }

    public void setToken(String token) {
        this.token = token;
    }

    public String getPlaylistResource() {
        return playlistResource;
    }

    public void setPlaylistResource(String playlistResource) {
        this.playlistResource = playlistResource;
    }
}

src/main/java/muxar/gateway/dto/MusicRecommendation.java
package muxar.gateway.dto;

import muxar.dto.MusicItem;

import java.util.List;

/**
 * Created by Alice on 1/29/2016.
 */
public class MusicRecommendation {
	private List<MusicItem> songsOfArtist;
	private List<MusicItem> songsOfUser;
	private List<MusicItem> songsOfOtherUsers;
	private List<MusicItem> songsFromFacebook;

	public MusicRecommendation() {
	}

	public MusicRecommendation(List<MusicItem> songsOfArtist,
			List<MusicItem> songsOfUser, List<MusicItem> songsOfOtherUsers,
			List<MusicItem> songsFromFacebook) {
		this.songsOfArtist = songsOfArtist;
		this.songsOfUser = songsOfUser;
		this.songsOfOtherUsers = songsOfOtherUsers;
		this.songsFromFacebook = songsFromFacebook;
	}

	public List<MusicItem> getSongsOfArtist() {
		return songsOfArtist;
	}

	public void setSongsOfArtist(List<MusicItem> songsOfArtist) {
		this.songsOfArtist = songsOfArtist;
	}

	public List<MusicItem> getSongsOfUser() {
		return songsOfUser;
	}

	public void setSongsOfUser(List<MusicItem> songsOfUser) {
		this.songsOfUser = songsOfUser;
	}

	public List<MusicItem> getSongsOfOtherUsers() {
		return songsOfOtherUsers;
	}

	public void setSongsOfOtherUsers(List<MusicItem> songsOfOtherUsers) {
		this.songsOfOtherUsers = songsOfOtherUsers;
	}

	public List<MusicItem> getSongsFromFacebook() {
		return songsFromFacebook;
	}

	public void setSongsFromFacebook(List<MusicItem> songsFromFacebook) {
		this.songsFromFacebook = songsFromFacebook;
	}
	
}

src/main/java/muxar/gateway/dto/MusicRequest.java
package muxar.gateway.dto;

public class MusicRequest {

	private String token;
	private String searchText;

	public MusicRequest() {
	}

	public MusicRequest(String token, String searchText) {
		super();
		this.token = token;
		this.searchText = searchText;
	}

	public String getToken() {
		return token;
	}

	public void setToken(String token) {
		this.token = token;
	}

	public String getSearchText() {
		return searchText;
	}

	public void setSearchText(String searchText) {
		this.searchText = searchText;
	}

}

src/main/java/muxar/gateway/dto/MusicWrapper.java
package muxar.gateway.dto;

import java.util.List;

import muxar.dto.MusicItem;

public class MusicWrapper {
	
	private List<MusicItem> musicList;

	public List<MusicItem> getMusicList() {
		return musicList;
	}

	public void setMusicList(List<MusicItem> musicList) {
		this.musicList = musicList;
	}


}

src/main/java/muxar/gateway/dto/PlayWrapper.java
package muxar.gateway.dto;

/**
 * Created by Alice on 1/29/2016.
 */
public class PlayWrapper {
    private String songResource;
    private String songName;
    private String artistResource;
    private String artistName;
    private String artistImage;
    private String token;
    private String userId;

    public PlayWrapper() {
    }

    public PlayWrapper(String songResource, String songName, String artistResource, String artistName, String artistImage, String token, String userId) {
        this.songResource = songResource;
        this.songName = songName;
        this.artistResource = artistResource;
        this.artistName = artistName;
        this.artistImage = artistImage;
        this.token = token;
        this.userId = userId;
    }

    public String getSongResource() {
        return songResource;
    }

    public void setSongResource(String songResource) {
        this.songResource = songResource;
    }

    public String getSongName() {
        return songName;
    }

    public void setSongName(String songName) {
        this.songName = songName;
    }

    public String getArtistResource() {
        return artistResource;
    }

    public void setArtistResource(String artistResource) {
        this.artistResource = artistResource;
    }

    public String getArtistName() {
        return artistName;
    }

    public void setArtistName(String artistName) {
        this.artistName = artistName;
    }

    public String getArtistImage() {
        return artistImage;
    }

    public void setArtistImage(String artistImage) {
        this.artistImage = artistImage;
    }

    public String getToken() {
        return token;
    }

    public void setToken(String token) {
        this.token = token;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }
}

src/main/java/muxar/gateway/dto/PlaylistAddWrapper.java
package muxar.gateway.dto;

/**
 * Created by Alice on 1/29/2016.
 */
public class PlaylistAddWrapper {
    private String playlistName;
    private String playlistPrivacy;
    private String token;
    private String userId;

    public PlaylistAddWrapper(String playlistName, String playlistPrivacy, String token, String userId) {
        this.playlistName = playlistName;
        this.playlistPrivacy = playlistPrivacy;
        this.token = token;
        this.userId = userId;
    }

    public String getPlaylistName() {
        return playlistName;
    }

    public void setPlaylistName(String playlistName) {
        this.playlistName = playlistName;
    }

    public String getPlaylistPrivacy() {
        return playlistPrivacy;
    }

    public void setPlaylistPrivacy(String playlistPrivacy) {
        this.playlistPrivacy = playlistPrivacy;
    }

    public String getToken() {
        return token;
    }

    public void setToken(String token) {
        this.token = token;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }
}

src/main/java/muxar/gateway/dto/PlaylistWrapper.java
package muxar.gateway.dto;

import muxar.playlist.domain.Playlist;

import java.util.List;

/**
 * Class used to wrap over list using rest template
 * Created by Alice on 1/28/2016.
 */
public class PlaylistWrapper {
    private List<Playlist> playlistList;

    public List<Playlist> getPlaylistList() {
        return playlistList;
    }

    public void setPlaylistList(List<Playlist> playlistList) {
        this.playlistList = playlistList;
    }
}

src/main/java/muxar/gateway/dto/RecommendationRequest.java
package muxar.gateway.dto;

/**
 * Created by Alice on 1/29/2016.
 */
public class RecommendationRequest {
    private String token;
    private String userId;

    public RecommendationRequest() {
    }

    public RecommendationRequest(String token, String userId) {
        this.token = token;
        this.userId = userId;
    }

    public String getToken() {
        return token;
    }

    public void setToken(String token) {
        this.token = token;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }
}

src/main/java/muxar/gateway/dto/RegisterWrapper.java
package muxar.gateway.dto;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Created by Alice on 1/29/2016.
 */
public class RegisterWrapper {

    @JsonProperty("access_token")
    private String token;
    private String username;
    private String userId;

    public RegisterWrapper() {
    }

    public RegisterWrapper(String token, String username, String userId) {
        this.token = token;
        this.username = username;
        this.userId = userId;
    }

    public String getToken() {
        return token;
    }

    public void setToken(String token) {
        this.token = token;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }
}

src/main/java/muxar/gateway/dto/TokenWrapper.java
package muxar.gateway.dto;

/**
 * Created by Alice on 1/29/2016.
 */
public class TokenWrapper {

    private String userId;
    private String token;

    public TokenWrapper(String userId, String token) {
        this.userId = userId;
        this.token = token;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getToken() {
        return token;
    }

    public void setToken(String token) {
        this.token = token;
    }
}

src/main/webapp/WEB-INF/views/main/editPlaylist.jsp
  <!-- Modal edit playlist-->
  <div class="modal fade" id="myModalEdit" role="dialog">
    <div class="modal-dialog">

      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Tracks</h4>
        </div>
        <div class="modal-body">
        
          <ul class="list-group">
  			<li class="list-group-item"><span class="badge">12</span> New</li>
  		  </ul>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
        </div>
      </div>
   </div>
 </div>

src/main/webapp/WEB-INF/views/main/header.jsp
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags"%>

<ul class="nav nav-pills">
    <li role="presentation" tab-value="home"><a href="home"><spring:message code="message.home" /></a></li>
    <li role="presentation" tab-value="playlist"><a href="playlist"><spring:message code="message.myPlaylists" /></a></li>
    <li role="presentation" tab-value="history"><a href="history"><spring:message code="message.history" /></a></li>
    <li role="presentation" tab-value="playlist-public"><a href="playlist-public"><spring:message code="message.publicPlaylists" /></a></li>
    <li role="presentation" tab-value="history" ><div class="fb-login-button" data-max-rows="1" data-size="large" data-show-faces="false" data-auto-logout-link="true" data-scope="public_profile,email,user_events, user_actions.music, user_likes" onlogin="checkLoginState();"></div>
    </li>
</ul>

<script type="text/javascript" src="${pageContext.servletContext.contextPath}/resources/js/jquery-1.11.3.js"></script>
<script type="text/javascript" src="${pageContext.servletContext.contextPath}/resources/js/header.js"></script>
<script type="text/javascript" src="${pageContext.servletContext.contextPath}/resources/js/facebook/login.js"></script>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>

src/main/webapp/WEB-INF/views/main/history.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<c:forEach items="${userHistory}" var="song">
	<div class="panel panel-default">
		<div class="panel-heading">
		</div>
		<div class="panel-body">
			<div class="left-panel">
				<span class="photo-song"><img width="65" height="65"
					src="${song.artist.image}" /> </span>
			</div>

			<div class="right-panel">
				<div class="song">
					<a href="${song.url}" target="_blank">${song.name}</a>
				</div>
				<div class="artist" dbpedia-owl="${song.artist.resourceName}">${song.artist.name}</div>
			</div>
		</div>

		<div class="panel-footer custom-footer" id="">
			<span class="glyphicon glyphicon-play-circle" id="playBtn"
				data-song-res="${song.resourceName}" data-song-name="${song.name}"
				data-song-artist-name="${song.artist.name}"
				data-song-artist-img="${song.artist.image}"
				data-song-artist-res="${song.artist.resourceName}"
				data-song-url="${song.url}"> </span>
		</div>
	</div>
</c:forEach>

<script>
	$(document).ready(function() {

		$(document).on('click', '#playBtn', function() {

			var songResource = $(this).attr('data-song-res');
			var songName = $(this).attr('data-song-name');
			var artistName = $(this).attr('data-song-artist-name');
			var artistImg = $(this).attr('data-song-artist-img');
			var artistResource = $(this).attr('data-song-artist-res');
			var url = $(this).attr('data-song-url');

			$.ajax({
				type : 'POST',
				url : '${pageContext.request.contextPath}/play',
				data : {
					songResource : songResource,
					songName : songName,
					artistResource : artistResource,
					artistName : artistName,
					artistImage : artistImg
				},
				success : function(data) {
					window.open(url);
				},
				error : function(data) {

				}
			});
		});
	});
</script>

src/main/webapp/WEB-INF/views/main/layout.jsp
<html>
<head>
<meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate" />
<meta http-equiv="Pragma" content="no-cache" />
<meta http-equiv="Expires" content="0" />
<%--START: here we should insert all css dependencies-> do not modify bootstrap, add another css file for custom CSS--%>
	<link href="${pageContext.servletContext.contextPath}/resources/css/header.css" rel="stylesheet" type="text/css" />
    <link href="${pageContext.servletContext.contextPath}/resources/css/bootstrap.css" rel="stylesheet" type="text/css" />
    <link href="${pageContext.servletContext.contextPath}/resources/css/body.css" rel="stylesheet" type="text/css" />
	<link href="${pageContext.servletContext.contextPath}/resources/css/main/home.css" rel="stylesheet" type="text/css" />
<%--END--%>
<%@ taglib uri="http://tiles.apache.org/tags-tiles" prefix="tiles"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>

</head>
<body>
<script>
	window.fbAsyncInit = function() {
		FB.init({
			appId      : '1661985780735748',
			xfbml      : true,
			version    : 'v2.5'
		});
	};

	(function(d, s, id){
		var js, fjs = d.getElementsByTagName(s)[0];
		if (d.getElementById(id)) {return;}
		js = d.createElement(s); js.id = id;
		js.src = "//connect.facebook.net/en_US/sdk.js";
		fjs.parentNode.insertBefore(js, fjs);
	}(document, 'script', 'facebook-jssdk'));
</script>


		<div class="header"><tiles:insertAttribute name="header" /></div>
        <div><tiles:insertAttribute name="search"/></div>
		<div id="body"><tiles:insertAttribute name="body" /></div>



<%--START: js dependecies, leave bootstrap dependencies untouched -> create new ones--%>
	<script type="text/javascript" src="${pageContext.servletContext.contextPath}/resources/js/jquery-1.11.3.js"></script>
	<script type="text/javascript" src="${pageContext.servletContext.contextPath}/resources/js/bootstrap.js"></script>

<%--END--%>
</body>
</html>

src/main/webapp/WEB-INF/views/main/login.jsp
<div class="login-container">
    <img class="logo" src="http://dreamatico.com/data_images/music/music-4.jpg"/>

    <div class="welcome">Welcome to <strong>MUXar</strong></div>

    <li role="presentation" tab-value="history" id="loginBtn">
        <div class="fb-login-button" data-max-rows="1" data-size="large" data-show-faces="false"
             data-auto-logout-link="true" data-scope="public_profile,email,user_events, user_actions.music, user_likes"
             onlogin="checkLoginState();"></div>
    </li>
    <script type="text/javascript"
            src="${pageContext.servletContext.contextPath}/resources/js/facebook/login.js"></script>
</div>

src/main/webapp/WEB-INF/views/main/search.jsp
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags"%>
<form>
	<div class="row">
		<div class="col-lg-6">
			<div class="input-group">
				<div id="info-sign" class="glyphicon glyphicon-info-sign" data-toggle="popover"
					 data-content="Search for <br/><strong>artist</strong>:Coldplay...<br/><strong>genre</strong>:rock...<br/>or</br> <strong>song name</strong>"
					  title="Hints" data-html="true" data-placement="bottom">
					 </div>

				<input id="inputSearch" type="text" class="form-control"
					placeholder="<spring:message code="message.searchFor" />"> <span class="input-group-btn">
					<button class="btn btn-default" type="button" id="searchBtn"
						name="searchBtn">Go!</button>

				</span>


			</div>
			<!-- /input-group -->
		</div>
		<!-- /.col-lg-6 -->
	</div>
</form>

<script>
	$(document).ready(function(){
		$('#info-sign[data-toggle="popover"]').popover();
	});
	$(document).on('click', '#searchBtn', function() {

		var inputText = document.getElementById("inputSearch").value;

		$.ajax({
			type : 'POST',
			url : '${pageContext.request.contextPath}/search',
			data : {
				searchText : inputText,
			},
			success : function(data) {
				document.open();
				document.write(data);
				document.close();
			},
			error : function(data) {
				document.open();
				document.write(data);
				document.close();
			}
		})
	});
</script>